name: seat_reservation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Logic
  flutter_bloc: ^7.0.0
  rxdart: ^0.27.1
  freezed: ^1.1.0
  
  # Data
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  uuid: ^3.0.4
  json_serializable: ^6.1.4

  # UI
  google_fonts: 2.2.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.21.0+1
  sizer: ^2.0.15

  # DI
  get_it: ^6.0.0

  # Logs
  logger: ^1.0.0
  
  # FP style classes
  dartz: ^0.10.0-nullsafety.1
  intl: ^0.17.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  analyzer: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/gt_walsheim_pro_regular.ttf
        - asset: assets/fonts/gt_walsheim_pro_bold.ttf
          weight: 700